### ISSUE TITLE
Chevron vertikal aligment litt "off"

### ISSUE THREAD

**Issue by bdahle** [navikt/nav-dekoratoren_legacy#1261]
Synes det ser litt rart ut, men er kanskje bare jeg som irriterer meg over det.

![image](https://user-images.githubusercontent.com/71373910/190972025-8254e5b9-ab56-4833-af62-ca208e41700a.png)

**Comment by macbruker** [comment]
Enig at det er noe rart der. Den står omtrent 1px høyere enn det som virker optisk vertikalt balansert.

**Comment by macbruker** [comment]
Ser følgende linje ligger i CSS-fila, og synes det blir finere uten den.

```css
.decorator-wrapper .lenke svg {
    top: -0.125em;
}
```
